spring.application.name=gateway

server.port=8085


# ======================
# EUREKA
# ======================

eureka.client.register-with-eureka=true

eureka.client.fetch-registry=true

eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/


# ======================
# GATEWAY ROUTES
# ======================

spring.cloud.gateway.routes[0].id=company_service
spring.cloud.gateway.routes[0].uri=http://company-service:8082
spring.cloud.gateway.routes[0].predicates[0]=Path=/company/**,/company


spring.cloud.gateway.routes[1].id=job_service
spring.cloud.gateway.routes[1].uri=http://job-service:8081
spring.cloud.gateway.routes[1].predicates[0]=Path=/job/**


spring.cloud.gateway.routes[2].id=review_service
spring.cloud.gateway.routes[2].uri=http://review-service:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/reviews/**


spring.cloud.gateway.routes[3].id=auth_service
spring.cloud.gateway.routes[3].uri=http://auth-service:8087
spring.cloud.gateway.routes[3].predicates[0]=Path=/auth/**


spring.cloud.gateway.routes[4].id=notification_service
spring.cloud.gateway.routes[4].uri=http://notification-service:8089
spring.cloud.gateway.routes[4].predicates[0]=Path=/notification/**


# ======================
# LOGGING
# ======================

logging.level.org.springframework.cloud.gateway=DEBUG